- name: 
  hosts: localhost
  become: false
  vars: 
    filename: pg_dump_{{ansible_date_time.date}}.sql
  tasks:
    - name: Create Postgres backup
      ansible.builtin.shell: kubectl exec deployments/postgres --namespace default -- bash -c 'pg_dumpall > /nas/{{filename}}'
