- name: 
  hosts: nas
  become: false
  tasks:
    - name: create restic snapshots
      ansible.builtin.shell: rbackup
    - name: prune restic snapshots
      ansible.builtin.shell: source /root/restic-env && restic forget --prune --keep-daily 10 --keep-weekly 1 --keep-monthly 1 --keep-yearly 1
