- name: 
  hosts: 
    - proxmox-1
    - proxmox-2
    - proxmox-3
  become: false
  tasks:
    - name: run collector
      ansible.builtin.shell: /opt/scrutiny/bin/scrutiny-collector-metrics-linux-amd64 run --api-endpoint http://192.168.1.230:30080
