- name: Update and Upgrade Server
  hosts: server
  gather_facts: false
  become: yes
  tasks:
    - name: Run Updates 
      apt:
        upgrade: yes
        update_cache: yes
- name: Update Docker Stacks
  hosts: server
  gather_facts: false
  tasks:
    - name: Update Stacks
      args:
        chdir: "/home/arya/.containers/"
      command: "./update.sh"
