- name: Update Debian Hosts
  hosts: debian
  tasks:
    - name: Update and upgrade apt packages
      become: false
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400
